export const films = [
    {
        id: 1,
        name: "Joker: Folie À Deux Điên Có Đôi",
        description: "“Joker: Folie à Deux” đưa Arthur Fleck đến trại tâm thần Arkham trong khi chờ xét xử cho những tội ác của hắn với tư cách là Joker. Trong lúc vật lộn với hai bản ngã của mình, Arthur không chỉ tìm thấy tình yêu đích thực mà còn khám phá ra âm nhạc luôn tồn tại trong con người hắn.",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f19%2f482wx722h%2D162630%2D190924%2D83.jpg",
        trailer: "Video unavailble",
        director: "Todd Phillips",
        actor: "Joaquin Phoenix, Zazie Beetz, Lady Gaga",
        genre: "Tâm lý, Tội Phạm",
        duration: 138,
        limit: "T16",
        star: 9,
        isPlaying: false
    },
    {
        id: 2,
        name: "Mộ Đom Đóm",
        description: "Bộ phim được đặt trong bối cảnh giai đoạn cuối chiến tranh thế giới thứ 2 ở Nhật, kể về câu chuyện cảm động về tình anh em của hai đứa trẻ mồ côi là Seita và Setsuko. Hai anh em mất mẹ trong một trận bom dữ dội của không quân Mỹ khi cha của chúng đang chiến đấu cho Hải quân Nhật. Hai đứa bé phải vật lộn giữa nạn đói, giữa sự thờ ơ của những người xung quanh (trong đó có cả người cô họ của mình)... Bi kịch thấm đẫm nước mắt.",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f24%2fb%2Dn%2Dsao%2Dc%2Da%2Dm%2Dom%2Dm%2Dpayoff%2Dposter%2Dkthuoc%2Dfacebook%2D154037%2D240924%2D43.jpg",
        trailer: "https://youtu.be/4vPeTSRd580",
        director: "Isao Takahata",
        actor: "Tsutomu Tatsumi, Ayano Shiraishi, Yoshiko Shinohara, Akemi Yamaguchi",
        genre: "Hoạt hình, Kịch",
        duration: 89,
        limit: "T13",
        star: 9.1,
        isPlaying: true
    },
    {
        id: 3,
        name: "Kumanthong",
        description: "Sau cái chết của con trai, Sarah tìm đến vùng đất tâm linh Thái Lan, khẩn cần một thầy tu nổi tiếng sử dụng tro cốt đứa bé để tạo nên bức tượng Kumanthong . Trong văn hóa tín ngưỡng dân gian huyền bí của Thái Lan, Kuman Thong - một bức tượng nhỏ chứa đựng linh hồn của một đứa trẻ sẽ mang lại may mắn cầu được ước thấy cho chủ nhân của nó. Bức tượng làm sống lại tình mẫu tử, nhưng cũng triệu hồi những oan hồn ngạ quỷ đến đoạt xác cả gia đình Sarah",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f19%2f482wx722h%2D162630%2D190924%2D83.jpg",
        trailer: "Video unavailble",
        director: "Xian Lim",
        actor: "Cindy Miranda, Althea Ruedas, Max Nattapol Diloknawarit",
        genre: "Kinh dị",
        duration: 101,
        limit: "T18",
        star: 7.1,
        isPlaying: true
    },
    {
        id: 4,
        name: "Khi Bầu Trời Gặp Biển Cả Ở Giữa Là Chúng Ta",
        description: "Một ngày nọ, cô gái trẻ tên Momo (Hibiki Kitazawa) tình cờ gặp Todo (Ayumu Nakajima), một người đàn ông 40 tuổi trong quán ăn. Mối quan hệ của họ bắt đầu chớm nở sau buổi tối đầy lãng mạn. Cả hai cùng nắm tay trải qua một hành trình kỳ lạ chất chứa nhiều nỗi buồn. Mỗi người đều có một quá khứ đau thương, chạy trốn khỏi thế giới để hướng đến nơi vô định.",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f08%2f20%2fhand%2D101227%2D200824%2D68.jpg",
        trailer: "Video unavailble",
        director: "Michio Koshikawa",
        actor: "Hibiki Kitazawa, Ayumu Nakajima",
        genre: "Lãng mạn",
        duration: 99,
        limit: "T16",
        star: 9.1,
        isPlaying: true
    },
    {
        id: 5,
        name: "Cô Dâu Hào Môn",
        description: "Phim lấy đề tài làm dâu hào môn và khai thác câu chuyện môn đăng hộ đối, lối sống và quy tắc của giới thượng lưu dưới góc nhìn hài hước và châm biếm.",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f28%2f181024%2Dco%2Ddau%2Dhao%2Dmon%2D145139%2D280924%2D78.png",
        trailer: "https://youtu.be/a0In_kqPVGM",
        director: "Vũ Ngọc Đãng",
        actor: "Uyển Ân, Samuel An, Thu Trang, Lê Giang, Kiều Minh Tuấn, NSND Hồng Vân,...",
        genre: "Tâm lý",
        duration: 114,
        limit: "T16",
        star: 9.3,
        isPlaying: true
    },
    {
        id: 6,
        name: "Tee Yod: Quỷ Ăn Tạng Phần 2",
        description: "Ba năm sau cái chết của Yam, Yak vẫn tiếp tục săn lùng linh hồn bí ẩn mặc áo choàng đen. Gặp một người đàn ông có triệu chứng giống Yam, Yak phát hiện ra người bảo vệ linh hồn, pháp sư ẩn dật Puang, sống trong một khu rừng đầy nguy hiểm. Giữa những phép thuật ma quỷ và những sinh vật nguy hiểm. Khi họ đuổi theo con quỷ mặc áo choàng đen, tiếng kêu đầy ám ảnh của Tee Yod sẽ quay trở lại một lần nữa...",
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f10%2f04%2f181024%2Dsneak%2Dtee%2Dyod%2D2%2D133440%2D041024%2D65.jpg",
        trailer: "https://youtu.be/Tx5JuN-5n8U",
        director: "Taweewat Wantha",
        actor: "Nadech Kugimiya, Denise Jelilcha Kapaun, Mim Rattawadee Wongthong, Junior Kajbhunditt Jaidee, Friend Peerakrit Phacharaboonyakiat, Nutthatcha Jessica Padovan",
        genre: "Kinh dị",
        duration: 111,
        limit: "T18",
        star: 8.1,
        isPlaying: true
    },
    {
        id: 7,
        name: "Hắn: Ác Mộng Quỷ Dữ",
        description: `Tại vùng nông thôn Nhật Bản, hàng loạt cái chết kỳ lạ đã xảy ra. Tất cả các nạn nhân đều có một điểm chung: trước khi chết, họ gặp một người đàn ông lạ mặt trong giấc mơ được biết đến với cái tên "This man ”. Và số phận của nữ chính Hana Yasaka cũng không ngoại lệ. Trước bi kịch, cô sống hạnh phúc bên chồng và con gái. Khi ngày càng có nhiều người thân chết, cô bắt đầu sợ ngủ. Cuối cùng, cô nhìn thấy "Người đàn ông" trong giấc mơ của mình... và cái kết tồi tệ nhất bắt đầu.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f08%2f20%2fz5748072757139%2D098d7f499c425ecb70ba5314e41623dc%2D101253%2D200824%2D22.jpg",
        trailer: "https://youtu.be/dTp7pUlNUMg",
        director: "Yujiro Amano",
        actor: "Arisa Deguchi, Minehiro Kinomoto, Miu Suzuki",
        genre: "Kinh dị",
        duration: 87,
        limit: "T18",
        star: 8.7,
        isPlaying: true
    },
    {
        id: 8,
        name: "Transformers Một",
        description: `Câu chuyện về nguồn gốc chưa từng được hé lộ của Optimus Prime và Megatron. Hai nhân vật được biết đến như những kẻ thù truyền kiếp, nhưng cũng từng là những người anh em gắn bó, đã thay đổi vận mệnh của Cybertron mãi mãi.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f11%2ftf1%2Dintl%2Dallspark%2Ddgtl%2Donline%2Dpayoff%2Dkeyart%2Dvie%2D400x633%2D134254%2D110924%2D51.jpg",
        trailer: "https://youtu.be/u2NuUWuwPCM",
        director: "Josh Cooley",
        actor: "Chris Hemsworth, Brian Tyree Henry, Scarlett Johansson",
        genre: "Phiêu lưu, Hoạt hình",
        duration: 104,
        limit: "T6",
        star: 8,
        isPlaying: true
    },
    {
        id: 9,
        name: "PHÉP MÀU GIỮA ĐÊM ĐÔNG",
        description: `Chuyển tới một ngôi trường mới, Julian tự cô lập bản thân, không để tâm với mọi người xung quanh. Biết vậy, bà nội của cậu, Sara Blum giãi bày tâm sự với Julian và tiết lộ cho cậu câu chuyện về thời niên thiếu của mình. Dưới thời Pháp bị Đức Quốc xã chiếm đóng, một cậu bé đã mạo hiểm tất cả để bảo vệ tính mạng bà. Trong đêm đen của chiến tranh và bom đạn, tình yêu, tình thân, tình người vẫn luôn hiện hữu.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f11%2ftf1%2Dintl%2Dallspark%2Ddgtl%2Donline%2Dpayoff%2Dkeyart%2Dvie%2D400x633%2D134254%2D110924%2D51.jpg",
        trailer: "https://youtu.be/Ooxp_5Kkee0",
        director: "Marc Forster",
        actor: " Helen Mirren, Gillian Anderson, Ariella Glaser, Orlando Schwerdt, Bryce Gheisar,…",
        genre: "Tâm Lý, Tình cảm",
        duration: 121,
        limit: "T16",
        star: 9.2,
        isPlaying: true
    },
    {
        id: 10,
        name: "KHÔNG NÓI ĐIỀU DỮ",
        description: `Một gia đình người Mỹ được mời đến nghỉ cuối tuần tại khu đất nông thôn bình dị của một gia đình người Anh thiện lành mà họ kết bạn trong kỳ nghỉ, câu chuyện bắt đầu khi kỳ nghỉ trong này mơ sớm biến thành một cơn ác mộng tâm lý kinh hoàng.`,
        imageThumnail: "https://iguov8nhvyobj.vcdn.cloud/media/catalog/product/cache/1/image/c5f0a1eff4c394a251036189ccddaacd/s/n/sne_intl_shhh_digital_1sheet_700x1000_vi.jpg",
        trailer: "https://youtu.be/VypozL0dbj4",
        director: "James Watkins",
        actor: "James McAvoy, Mackenzie Davis, Scoot McNairy,...",
        genre: "Hồi hộp, Kinh Dị, Tâm Lý",
        duration: 109,
        limit: "T18",
        star: 0,
        isPlaying: false
    },
    {
        id: 11,
        name: "Thần Dược",
        description: `Elizabeth Sparkle, minh tinh sở hữu vẻ đẹp hút hồn cùng với tài năng được mến mộ nồng nhiệt. Khi đã trải qua một thời kỳ đỉnh cao, nhan sắc dần tàn phai, cô tìm đến những kẻ buôn lậu để mua 1 loại thuốc bí hiểm nhằm “thay da đổi vận”, tạo ra một phiên bản trẻ trung hơn của chính mình.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f10%2f08%2fscreenshot%2D2024%2D10%2D08%2D164725%2D164802%2D081024%2D67.png",
        trailer: "https://youtu.be/U-RxVJrLKrk",
        director: "Coralie Fargeat",
        actor: "Demi Moore, Dennis Quaid, Margaret Qualley",
        genre: "Kinh dị, Khoa học, viễn tưởng",
        duration: 138,
        limit: "T18",
        star: 0,
        isPlaying: false
    },
    {
        id: 12,
        name: "Domino: Lối Thoát Cuối Cùng",
        description: `Sau khi cha bị kẻ ác sát hại, từ người ngoài cuộc, An (Thuận Nguyễn) từng bước bị kéo vào cuộc chiến của các phe đảng xã hội đen. An một mình sẽ phải đối mặt với những nguy hiểm đe dọa đến cả tính mạng.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f24%2fscreenshot%2D2024%2D09%2D24%2D133906%2D133948%2D240924%2D80.png",
        trailer: "https://youtu.be/UXXBy5n_22g",
        director: "Nguyễn Phúc Huy Cương",
        actor: "Thuận Nguyễn, Quốc Cường, Huỳnh Anh Tuấn, Henry Nguyễn, Cát Hạ",
        genre: "Hành động, Hồi hộp, Ly kì",
        duration: 120,
        limit: "T18",
        star: 0,
        isPlaying: false
    },
    {
        id: 13,
        name: "Robot Hoang Dã",
        description: `Cuộc phiêu lưu hoành tráng theo chân hành trình của một robot — đơn vị ROZZUM 7134, gọi tắt là Roz. Roz vô tình dạt vào hoang đảo sau một sự cố và nơi đây trở thành địa điểm sống mới của cô. Tại đây, Roz kết thân và nhận nuôi một chú ngỗng con, đặt tên là Brightbill. Roz và Brightbill dần dần thân thiết với các bạn thú trên đảo, song sau đó phải chống chọi, bảo vệ “nhà mới” trước sự xâm lăng của nhà máy từng sản xuất ra Roz.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f25%2ftwr%2Dsneakshow%2D400x633%2D102333%2D250924%2D81.jpg",
        trailer: "https://youtu.be/67vbA5ZJdKQ",
        director: "Chris Sanders",
        actor: "Lupita Nyong'o, Pedro Pascal, Catherine O’hara, Bill Nighy,...",
        genre: "Phiêu lưu, Hoạt hình",
        duration: 102,
        limit: "T6",
        star: 0,
        isPlaying: false
    },
    {
        id: 14,
        name: "Ngày Xưa Có Một Chuyện Tình",
        description: `Ngày xưa có một chuyện tình kể về tình bạn, tình yêu giữa hai chàng trai và một cô gái từ thuở ấu thơ cho đến khi trưởng thành, trước những thử thách của số phận. Bộ ba Phúc, Vinh, Miền - theo như lời của chính nhà văn Nguyễn Nhật Ánh - đã đi đến tận cùng của một chuyện tình.`,
        imageThumnail: "https://files.betacorp.vn/media%2fimages%2f2024%2f09%2f26%2fscreenshot%2D2024%2D09%2D26%2D163000%2D163110%2D260924%2D75.png",
        trailer: "https://youtu.be/IcpKkCzvcU4",
        director: "Trịnh Đình Lê Minh",
        actor: "Avin Lu, Ngọc Xuân, Đỗ Nhật Hoàng, Thanh Tú, Bảo Tiên, Hạo Khang",
        genre: "Tình cảm",
        duration: 120,
        limit: "T6",
        star: 0,
        isPlaying: false
    },
]